import { StyleSheet } from "react-native";

const styles = StyleSheet.create({
  container: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    paddingTop: 0,
  },
  background: {
    flex: 1,
    alignItems: "center",
  },
  input: {
    backgroundColor: "#F0EFEC",
    height: 40,
    width: 360,
    borderWidth: 1,
    borderColor: "#586F7C",
    padding: 8,
    borderRadius: 5,
    marginBottom: 15,
  },
  inputDetails: {
    backgroundColor: "#F0EFEC",
    height: 80,
    width: 360,
    borderWidth: 1,
    borderColor: "#586F7C",
    padding: 10,
    borderRadius: 5,
    marginBottom: 15,
  },
  label: {
    color: "black",
    padding: 0,
    margin: 2,
    marginLeft: 0,
    alignItems: "center",
  },
  labelType: {
    color: "black",
    padding: 0,
    margin: 2,
    marginLeft: 0,
    alignItems: "center",
    marginTop: 15,
  },
  labelDetails: {
    color: "black",
    padding: 0,
    margin: 2,
    marginLeft: 0,
    alignItems: "center",
    marginTop: 15,
  },
  container: {
    justifyContent: "center",
    alignItems: "center",
    padding: 2,
  },
  title: {
    fontWeight: "bold",
    padding: 10,
  },
  circles: {
    flexDirection: "row",
    margin: 10,
  },
  button: {
    backgroundColor: "#A6AB72",
    padding: 8,
    borderRadius: 75,
    alignItems: "center",
    justifyContent: "center",
    alignContent: "center",
    marginBottom: 10,
    width: 100,
    height: 100,
    margin: 15,
  },
  buttonDate: {
    backgroundColor: "#83ADB4",
    padding: 8,
    borderRadius: 75,
    alignItems: "center",
    justifyContent: "center",
    alignContent: "center",
    marginBottom: 10,
    width: 100,
    height: 100,
    margin: 15,
  },
  buttonText: {
    color: "#586F7C",
    fontWeight: "700",
    fontSize: 12,
    marginBottom: 5,
  },
  dropdown: {
    width: 250,
    height: 30,
    alignSelf: "center",
  },
  buttonNormal: {
    backgroundColor: "#BC9C22",
    borderRadius: 20,
    alignItems: "center",
    marginTop: 10,
    padding: 10,
  },
  buttonTextLast: {
    color: "black",
    fontWeight: "700",
    fontSize: 12,
  },
});

export default styles;
